##
 # A reusable Gradle build workflow for testing for breaking changes.
 #
 # This workflow can be called from workflows in other repos with:
 # ```
 # jobs:
 #   <job-id>:
 #     uses: brightsparklabs/github-actions/.github/workflows/test-gradle-build.yml@<version>
 # ```
 #
 # See https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
 # ______________________________________________________________________________
 #
 # Maintained by brightSPARK Labs.
 # www.brightsparklabs.com
 ##

name: Build with Gradle

on:
  # This workflow will run when called by another workflow.
  workflow_call:
    inputs:
      os:
        description: "The operating system to run the Gradle build on. Defaults to `ubuntu-latest`."
        default: ubuntu-latest
        required: false
        type: string

jobs:
  # Build with Gradle.
  gradle-build:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetch all commits to ensure `git describe` returns correct version.
          fetch-depth: 0
      - name: Fix tag
        # Workaround actions/checkout bug. See:
        # - https://github.com/actions/checkout/issues/290
        # - https://github.com/actions/checkout/issues/882
        if: github.ref_type == 'tag'
        run: git fetch -fv origin tag ${{ github.ref_name }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"
      - name: Execute Gradle build
        run: ./gradlew build
